/* Automatically generated by "build-radpaths-h" */
#define LOGDIR		"/usr/local/var/log/radius"
#define LIBDIR		"/usr/local/lib"
#define RADDBDIR	"/usr/local/etc/raddb"
#define RUNDIR		"/usr/local/var/run"
#define SBINDIR		"/usr/local/sbin"
#define RADIR		"/usr/local/var/log/radius/radacct"
